# Generated by Django 5.2.5 on 2025-08-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
