# Generated by Django 5.2.5 on 2025-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapi', '0002_member_day_member_payment_id_member_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
